import { Injectable } from '@angular/core';

@Injectable()
export class AtividadesRec {
    lista = 
    [
    {
        'OfferID': '1',
        'dominios': {'Cognition': 90,
        'Attitude': 60,
        'Depression': 40,
        'Sensorial': 30,
        'Functional': 10,
        'Nutrition': 10,
        'Cardiovascular': 90,
        'Prescriptions': 10,
        'SocialSupport': 80,
        'Environment': 30,
        'Violence': 40,
        'Falls': 10},
        'Bene': 'Melhora a Cognição; Ajuda no aprendizado; Auxilia a criar e fortalecer vínculos sociais',
        'Desc' : 'Curso de ativação da memória e lógica em grupos de discussão',
        'Rest' : 'Não atende deficientes visuais e auditivos',
        'Acti' : 'Sim',
        'Type' : 'Cognitivo, Social',
        'Sche' : 'Segunda e Quarta das 8:00 às 9:00',
        'Time' : '1:00 hora',
        'Grou' : 'Grupo',
        'Cost' : 'Grátis',
        'LowP' : 'Sim',
        'Part' : 'Sim',
        'Loca' : 'Sesc',
        'Enve' : 'Interno',
        'Dist' : '3 KM',
        'PuTr' : '25 minutos',
        'Scor' : 0
    },

    {
        'OfferID': '2',
        'dominios': {'Cognition': 20,
        'Attitude': 90,
        'Depression': 80,
        'Sensorial': 10,
        'Functional': 10,
        'Nutrition': 10,
        'Cardiovascular': 10,
        'Prescriptions': 20,
        'SocialSupport': 40,
        'Environment': 20,
        'Violence': 60,
        'Falls': 30},
        'Bene': 'Aumenta autoestima, ajuda no autoconhecimento, permite ao idoso entender o envelhecimento, discute limitações decorrentes do envelhecimento',
        'Desc' : 'Palestras motivacionais de autoconhecimento e autoaceitação',
        'Rest' : 'Não atende deficientes visuais e auditivos',
        'Acti' : 'Sim',
        'Type' : 'Cognitivo, Social',
        'Sche' : 'Terça e Quinta das 10:00 às 12:00',
        'Time' : '2:00 horas',
        'Grou' : 'Grupo',
        'Cost' : 'Grátis',
        'LowP' : 'Sim',
        'Part' : 'Sim',
        'Loca' : 'USP',
        'Enve' : 'Interno',
        'Dist' : '6 KM',
        'PuTr' : '45 minutos',
        'Scor' : 0
    },

   {
        'OfferID': '3',
        'dominios': {'Cognition': 20,
        'Attitude': 40,
        'Depression': 50,
        'Sensorial': 80,
        'Functional': 80,
        'Nutrition': 60,
        'Cardiovascular': 50,
        'Prescriptions': 60,
        'SocialSupport': 60,
        'Environment': 60,
        'Violence': 60,
        'Falls': 60},
        'Bene': 'Ajuda entender e contornar deficiência, mostra os principais problemas enfrentados pelas pessoas deficientes, discute formas do deficiente superar obstáculos',
        'Desc' : 'Atividades prática: Como conviver com deficiências em um mundo não adaptado',
        'Rest' : '',
        'Acti' : 'Sim',
        'Type' : 'Cognitivo, Social',
        'Sche' : 'Terça e Quinta das 16:00 às 18:00',
        'Time' : '2:00 horas',
        'Grou' : 'Grupo',
        'Cost' : 'Gastos com materiais R$ 100,00',
        'LowP' : 'Não',
        'Part' : 'Não',
        'Loca' : 'Unimed',
        'Enve' : 'Interno e Externo',
        'Dist' : '2 KM',
        'PuTr' : '20 minutos',
        'Scor' : 0
    },

    {
        'OfferID': '4',
        'dominios': {'Cognition': 10,
        'Attitude': 50,
        'Depression': 60,
        'Sensorial': 10,
        'Functional': 20,
        'Nutrition': 90,
        'Cardiovascular': 70,
        'Prescriptions': 50,
        'SocialSupport': 60,
        'Environment': 10,
        'Violence': 10,
        'Falls': 50},
        'Bene': 'Ensina maneiras de cozinhar sem perder as qualidades nutricionais, discute o valor nutricional dos alimentos, demonstra a importância de se preparar as refeições',
        'Desc' : 'Curso: Comida boa não é cara, como preparar pratos nutritivos e saborosos gastando pouco',
        'Rest' : 'Não adequado a pessoas com problemas para manipular objetos, risco de queimaduras',
        'Acti' : 'Sim',
        'Type' : 'Cognitivo, Social',
        'Sche' : 'Segunda e Quarta das 10:00 às 12:00',
        'Time' : '2:00 horas',
        'Grou' : 'Grupo',
        'Cost' : 'Gastos com materiais R$ 80,00',
        'LowP' : 'Não',
        'Part' : 'Não',
        'Loca' : 'Uniara',
        'Enve' : 'Interno',
        'Dist' : '6 KM',
        'PuTr' : '60 minutos',
        'Scor' : 0
    },

    {
        'OfferID': '5',
        'dominios': {'Cognition': 10,
        'Attitude': 60,
        'Depression': 10,
        'Sensorial': 10,
        'Functional': 30,
        'Nutrition': 30,
        'Cardiovascular': 30,
        'Prescriptions': 90,
        'SocialSupport': 40,
        'Environment': 30,
        'Violence': 30,
        'Falls': 40},
        'Bene': 'Discute as casses terapeuticas, ensina sobre os problemas da automedicação, aborda a importância de seguir as ordens médicas',
        'Desc' : 'Ciclo de palestras: Remédios e problemas da automedicação. Riscos da não obidiência às recomendações médicas',
        'Rest' : '',
        'Acti' : 'Sim',
        'Type' : 'Cognitivo, Social',
        'Sche' : 'Segunda e Quarta das 10:00 às 12:00',
        'Time' : '2:00 horas',
        'Grou' : 'Grupo',
        'Cost' : 'Gastos com materiais R$ 80,00',
        'LowP' : 'Não',
        'Part' : 'Não',
        'Loca' : 'Uniara',
        'Enve' : 'Interno',
        'Dist' : '6 KM',
        'PuTr' : '60 minutos',
        'Scor' : 0
    },

    {
        'OfferID': '6',
        'dominios': {'Cognition': 30,
        'Attitude': 70,
        'Depression': 50,
        'Sensorial': 20,
        'Functional': 10,
        'Nutrition': 50,
        'Cardiovascular': 40,
        'Prescriptions': 10,
        'SocialSupport': 80,
        'Environment': 20,
        'Violence': 80,
        'Falls': 30},
        'Bene': 'Discute as relações humans, ensina como lidar com conflitos, ajuda no fortalecimento de vículos sociais, incentiva o aumento da redes socias',
        'Desc' : 'Curso: Redes sociais, como criá-las e mantê-las',
        'Rest' : 'Necessário possui um celular com acesso a internet',
        'Acti' : 'Sim',
        'Type' : 'Cognitivo, Social',
        'Sche' : 'Sexta das 10:00 às 12:00',
        'Time' : '2:00 horas',
        'Grou' : 'Grupo',
        'Cost' : '',
        'LowP' : 'Não',
        'Part' : 'Não',
        'Loca' : 'Uniara',
        'Enve' : 'Interno e Externo',
        'Dist' : '6 KM',
        'PuTr' : '60 minutos',
        'Scor' : 0
    },

    {
        'OfferID': '7',
        'dominios': {'Cognition': 60,
        'Attitude': 60,
        'Depression': 60,
        'Sensorial': 10,
        'Functional': 50,
        'Nutrition': 10,
        'Cardiovascular': 20,
        'Prescriptions': 10,
        'SocialSupport': 50,
        'Environment': 80,
        'Violence': 30,
        'Falls': 60},
        'Bene': 'Fala sobre a importância dos dispositivos de apoio e segurança na casa dos idosos, demonstra e explica os principais dispositivos de apoio e segurança para os idosos',
        'Desc' : 'Curso multidisciplinar: Criando ambientes seguros para idosos',
        'Rest' : 'Não adaptados para pessoas com deficiência visual, auditiva ou que necessitem muletas ou cadeira de rodas',
        'Acti' : 'Sim',
        'Type' : 'Cognitivo',
        'Sche' : 'Segunda a sexta das 08:00 às 12:00 durante duas semanas',
        'Time' : '40:00 horas (total)',
        'Grou' : 'Grupo',
        'Cost' : 'R$ 1.000,00',
        'LowP' : 'Não',
        'Part' : 'Não',
        'Loca' : 'Unip',
        'Enve' : 'Interno e Externo',
        'Dist' : '10 KM',
        'PuTr' : '90 minutos',
        'Scor' : 0
    },

    {
        'OfferID': '8',
        'dominios': {'Cognition': 20,
        'Attitude': 60,
        'Depression': 60,
        'Sensorial': 50,
        'Functional': 50,
        'Nutrition': 30,
        'Cardiovascular': 60,
        'Prescriptions': 10,
        'SocialSupport': 50,
        'Environment': 30,
        'Violence': 10,
        'Falls': 60},
        'Bene': 'Aumenta a capacidade cardiorespiratória, melhora autoestima, melhora o equilíbrio, ajuda nos relacionamentos sociais, fortalece as pernas, ajuda no humor, ajuda no sono',
        'Desc' : 'Dança de salão para a terceira idade, inclusiva para pessoas com deficiência',
        'Rest' : '',
        'Acti' : 'Sim',
        'Type' : 'Física,Social',
        'Sche' : 'Segunda a sexta das 21:00 às 23:00',
        'Time' : 'O idoso participa o tempo que quiser',
        'Grou' : 'Grupo',
        'Cost' : 'Grátis',
        'LowP' : 'Sim',
        'Part' : 'Sim',
        'Loca' : 'USP',
        'Enve' : 'Interno',
        'Dist' : '1 KM',
        'PuTr' : '15 minutos',
        'Scor' : 0
    },

    {
        'OfferID': '9',
        'dominios': {'Cognition': 30,
        'Attitude': 60,
        'Depression': 50,
        'Sensorial': 30,
        'Functional': 60,
        'Nutrition': 30,
        'Cardiovascular': 80,
        'Prescriptions': 10,
        'SocialSupport': 10,
        'Environment': 10,
        'Violence': 10,
        'Falls': 70},
        'Bene': 'Fortalece a musculatura, aumenta a capacidade cardiovascular, melhora o humor, melhora o equilíbrio',
        'Desc' : 'Natação para a terceira idade',
        'Rest' : 'Pessoas com problemas graves de locomoção necessitam de um acompanhante',
        'Acti' : 'Sim',
        'Type' : 'Esportivo',
        'Sche' : 'Segunda e Quinta das 08:00 às 09:00',
        'Time' : '10:00 hora',
        'Grou' : 'Individual',
        'Cost' : 'R$ 120,00 por mês',
        'LowP' : '20% desconto baixa renda',
        'Part' : 'Sim, desconto de 20% indicados. Cumulativo com o baixa renda.',
        'Loca' : 'Clube São Carlos',
        'Enve' : 'Interno',
        'Dist' : '2 KM',
        'PuTr' : '20 minutos',
        'Scor' : 0
    },

    {
        'OfferID': '10',
        'dominios': {'Cognition': 50,
        'Attitude': 60,
        'Depression': 60,
        'Sensorial': 30,
        'Functional': 60,
        'Nutrition': 30,
        'Cardiovascular': 60,
        'Prescriptions': 10,
        'SocialSupport': 30,
        'Environment': 20,
        'Violence': 10,
        'Falls': 70},
        'Bene': 'Melhora a capacidade cardiovascular, melhora o equilíbrio, aumenta a flexibilidade, incentiva atividade em grupo, melhora o humor, trabalha o autoconhecimento',
        'Desc' : 'Hidroginástica para a terceira idade',
        'Rest' : 'pessoas com deficiência visual ou auditiva podem se sentir desconfortáveis durante a aulas',
        'Acti' : 'Sim',
        'Type' : 'Esportivo e Social',
        'Sche' : 'Terça e Quinta das 09:00 às 10:00',
        'Time' : '1:00 hora',
        'Grou' : 'Grupo',
        'Cost' : 'R$ 60,00',
        'LowP' : 'Sim, o preço já é reduzido',
        'Part' : 'Sim, o preço já é reduzido',
        'Loca' : 'Clube São Carlos',
        'Enve' : 'Interno',
        'Dist' : '1 KM',
        'PuTr' : '15 minutos',
        'Scor' : 0
    }

    ];

    public getLista() {
        return this.lista;
    }
}